### ISSUE TITLE
Windows Server 2022 - multiple adapter team not working

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#139]
If multiple adapters added to a overlay network following error occurs: 

``` text
Attaching a virtual switch to an LBFO team is deprecated. Switch Embedded Teaming (SET) is an inbox replacement for this functionality. For more information on LBFO deprecation please see https://aka.ms/LBFODeprecation. To override this block, use the AllowNetLbfoTeams option in New-VMSwitch.
 ---> Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException: Failed while adding virtual Ethernet switch connections.

Attaching a virtual switch to an LBFO team is deprecated. Switch Embedded Teaming (SET) is an inbox replacement for this functionality. For more information on LBFO deprecation please see https://aka.ms/LBFODeprecation. To override this block, use the AllowNetLbfoTeams option in New-VMSwitch.
   at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
   at Microsoft.Virtualization.Client.Management.View.EndMethodReturnEnumeration[AffectedElementType](IVMTask task, VirtualizationOperation operation)
   at Microsoft.Virtualization.Client.Management.VirtualSwitchManagementServiceView.EndAddVirtualSwitchPorts(IVMTask task)
   at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
   at Microsoft.HyperV.PowerShell.VMSwitch.AddConnections(IOperationWatcher operationWatcher, Boolean addExternalPort, Boolean addInternalPort, String[] externalNicName, String[] externalNicDescription)
   at Microsoft.HyperV.PowerShell.VMSwitch.ChangeSwitchType(VMSwitchType newType, VMSwitchType currentType, Boolean allowManagementOS, String[] externalNicName, String[] externalNicDescription, IOperationWatcher operationWatcher)
   at Microsoft.HyperV.PowerShell.VMSwitch.ConfigureConnections(VMSwitchType switchType, Boolean allowManagementOS, String[] externalNicName, String[] externalNicDescription, IOperationWatcher operationWatcher)
   at Microsoft.HyperV.PowerShell.Commands.NewVMSwitch.CreateObjects(IOperationWatcher operationWatcher)
   --- End of inner exception stack trace ---
```

**Comment by fw2568** [comment]
We will have to verify if Switch Embedded Teaming (SET) will work with openvswitch or if we have to set the AllowNetLbfoTeams on WinServer 2022 and later.
