### ISSUE TITLE
NullReferenceException in inventory

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#261]
Environment: Windows Server 2022
Custom Agent Settings path for volumes

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eryph.Modules.Controller.Inventory.UpdateInventoryCommandHandlerBase.SelectAllParentDisks(DiskInfo diskInfo) in D:\a\1\s\src\modules\src\Eryph.Modules.Controller\Inventory\UpdateInventoryCommandHandlerBase.cs:line 250
   at LanguageExt.Seq`1.<>c__DisplayClass66_0`1.<<Map>g__Yield|0>d.MoveNext()
   at LanguageExt.Enum`1.Get(Int32 index)
   at LanguageExt.SeqLazy`1.GetEnumerator()+MoveNext()
   at LanguageExt.Seq`1.<Bind>g__Yield|68_0[B](Seq`1 ma, Func`2 bnd)+MoveNext()
   at LanguageExt.Enum`1.Get(Int32 index)
   at LanguageExt.SeqLazy`1.GetEnumerator()+MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Eryph.Modules.Controller.Inventory.UpdateInventoryCommandHandlerBase.ResolveAndUpdateDisks(List`1 diskInfos, DateTimeOffset timestamp, CatletFarm hostMachine)
   at Eryph.Modules.Controller.Inventory.UpdateInventoryCommandHandlerBase.UpdateVMs(DateTimeOffset timestamp, IEnumerable`1 vmList, CatletFarm hostMachine) in D:\a\1\s\src\modules\src\Eryph.Modules.Controller\Inventory\UpdateInventoryCommandHandlerBase.cs:line 58
   at Eryph.Modules.Controller.Inventory.UpdateVMHostInventoryCommandHandler.Handle(UpdateVMHostInventoryCommand message) in D:\a\1\s\src\modules\src\Eryph.Modules.Controller\Inventory\UpdateVMHostInventoryCommandHandler.cs:line 45
   at Rebus.Pipeline.Receive.HandlerInvoker`1.Invoke()
   at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Sagas.Exclusive.EnforceExclusiveSagaAccessIncomingStepBase.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.UnitOfWork.UnitOfWorkStep`1.Process(IncomingStepContext context, Func`1 next)
   at Rebus.UnitOfWork.UnitOfWorkStep`1.Process(IncomingStepContext context, Func`1 next)
   at Rebus.UnitOfWork.UnitOfWorkStep`1.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Retry.Simple.FailedMessageWrapperStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Retry.Simple.DefaultRetryStep.Process(IncomingStepContext context, Func`1 next)

**Comment by fw2568** [comment]
This issue is solved with current inventory implementation.
