### ISSUE TITLE
Service startup: Host Info not available

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#73]
During startup as service host info may not already be available: 

---> (Inner Exception #4) SimpleInjector.ActivationException: failed to query for hyper-v host settings
 ---> System.Exception: failed to query for hyper-v host settings
   at Eryph.Modules.VmHostAgent.HostSettingsBuilder.GetHostSettings() in D:\Source\Repos\eryph\eryph\src\modules\src\Eryph.Modules.VmHostAgent\HostSettingsBuilder.cs:line 27
   at Eryph.Modules.VmHostAgent.Inventory.InventoryRequestedEventHandler..ctor(IBus bus, IPowershellEngine engine, ILogger log, IHostInfoProvider hostInfoProvider) in D:\Source\Repos\eryph\eryph\src\modules\src\Eryph.Modules.VmHostAgent\Inventory\InventoryRequestedEventHandler.cs:line 35
   at lambda_method120(Closure )
   at SimpleInjector.InstanceProducer.GetInstance()
   --- End of inner exception stack trace ---

**Comment by fw2568** [comment]
this should be solved by adding depends to Service installer in project https://github.com/dbosoft/dotnet-ovn.
